# Generated by Django 5.1 on 2024-08-24 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tendering", "0002_remove_lot_participant_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="participant",
            field=models.ManyToManyField(
                through="tendering.Bid", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
